# Generated by Django 5.1 on 2024-09-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'Data'},
        ),
        migrations.AddField(
            model_name='data',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='exclude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='focus_column',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
