# Generated by Django 5.1 on 2024-09-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_data_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='focus_column',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
