# Generated by Django 5.1 on 2024-09-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_alter_data_focus_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='focus_column',
            field=models.CharField(max_length=100),
        ),
    ]
