# Generated by Django 5.1 on 2024-09-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_alter_data_focus_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='analysis_status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20),
        ),
    ]
